### ISSUE TITLE
NTR for sediment when the size fraction is unknown (BODCNVS-1088)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S26#6]
To match Sandre: Fraction inconnue de sédiments (https://id.eaufrance.fr/fan/30) for SIMM parameter project.

**Comment by gwemon** [comment]
MAT01994 queued for publication

**Comment by danibodc** [comment]
Term is live on the NVS:
http://vocab.nerc.ac.uk/collection/S26/current/MAT01994/
